version: "3.9"

services:
  kom-tracker-api:
    image: karql/kom-tracker-kom-tracker-api:latest
    restart: always
    environment:
      ConnectionStrings__DB: ${CONNECTION_STRING}
      StravaApiClientConfiguration__ClientID: ${STRAVA_API__CLIENT_ID}
      StravaApiClientConfiguration__ClientSecret: ${STRAVA_API_CLIENT_SECRET}
    ports:
      - 8888:80
  
  

  