version: "3.9"

services:
  nginx-reverse-proxy:
    image: karql/kom-tracker-nginx:1.21-alpine
    restart: always
    ports:
      #- "80:80"
      #- "443:443"
      - 9999:9999
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/htpasswd:/etc/nginx/htpasswd:ro   
      - ./conf/nginx/ssl:/etc/nginx/ssl

      # Certbot
      - ./volumes/reverse-proxy/certbot/conf:/etc/letsencrypt
      - ./volumes/reverse-proxy/certbot/www:/var/www/certbot   

  # certbot only for same paths like in production ;)
  certbot:
    image: certbot/certbot
    #restart: unless-stopped
    volumes:
      - ./volumes/reverse-proxy/certbot/conf:/etc/letsencrypt
      - ./volumes/reverse-proxy/certbot/www:/var/www/certbot   

  kom-tracker-api:
    image: karql/kom-tracker-api:latest
    restart: always
    environment:
      ConnectionStrings__DB: ${CONNECTION_STRING}
      ApplicationConfiguration__TrackKomsJobEnabled: "false"
      ApplicationConfiguration__RefreshSegmentsJobEnabled: "false"
      ApplicationConfiguration__MasterStravaAthleteId: ${APP_CONF_MASTER_STRAVA_ATHLETE_ID}
      ApplicationConfiguration__SendinBlueConfiguration__Enabled: "false"
      ApplicationConfiguration__SendinBlueConfiguration__ApiKey: ${APP_CONF_SENDINBLUE_API_KEY}
      ApplicationConfiguration__SendinBlueConfiguration__TestMail: karql.pl@gmail.com
      ApplicationConfiguration__SendinBlueConfiguration__ChangeEmailConfirmationTemplateId: 7
      ApplicationConfiguration__SendinBlueConfiguration__TrackKomsTemplateId: 3
      StravaApiClientConfiguration__ClientID: ${STRAVA_API_CLIENT_ID}
      StravaApiClientConfiguration__ClientSecret: ${STRAVA_API_CLIENT_SECRET}
      IdentityConfiguration__IdentityUrl: https://localhost:9999/kom-tracker-api/identity
      IdentityConfiguration__Authority: http://kom-tracker-api/identity
      IdentityConfiguration__RequireHttpsMetadata: "false"
      IdentityConfiguration__RedirectUris__0: https://localhost
      IdentityConfiguration__PostLogoutRedirectUris__0: https://localhost
      Serilog__MinimumLevel__Default: Debug
      ASPNETCORE_ENVIRONMENT: Development

  kom-tracker-web:
    image: karql/kom-tracker-web:latest
    restart: always
    volumes:
      - ./conf/kom-tracker-web/appsettings.json:/app/appsettings.json