---
- name: prepare daemon directory
  file:
    path: '/etc/docker'
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Copy daemon configuration
  copy:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart docker
