---
- name: register containers list before restart
  command: "docker container ls --format '{{ '{{' }} .ID {{ '}}' }} {{ '{{' }} .Names {{ '}}' }} {{ '{{' }} .Image {{ '}}' }}'"
  register: containers_list_before
  changed_when: false
  ignore_errors: yes

- name: print containers list before restart
  debug:
    var: containers_list_before.stdout_lines

- block:
  - include: docker_install.yml

  - include: daemon_configuration.yml