---
- name: Check current docker compose version
  command: /usr/local/bin/docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  ignore_errors: yes
  check_mode: no

- name: Install or upgrade docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
    dest: /usr/local/bin/docker-compose
    mode: '+x'
    force: yes
  environment: "{{ proxy_env | default(omit) }}"
  when: >
    docker_compose_current_version.rc != 0 or
    (( docker_compose_current_version.stdout_lines[0].split(" ")[2] | replace(',', '') < docker_compose_version ) and docker_compose_update )
