// <auto-generated />
using System;
using KomTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KomTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KOMDBContext))]
    [Migration("20260817192631_AddComponentAndWarehouseTables")]
    partial class AddComponentAndWarehouseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteClubEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<long>("ClubId")
                        .HasColumnType("bigint")
                        .HasColumnName("club_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.HasKey("AthleteId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("athlete_club", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Profile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile");

                    b.Property<string>("ProfileMedium")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_medium");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("AthleteId");

                    b.ToTable("athlete", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteStatsEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("stats_json");

                    b.HasKey("AthleteId");

                    b.ToTable("athlete_stats", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Bike.BikeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<decimal>("InitialDistanceKm")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_distance_km");

                    b.Property<decimal?>("InitialElevationM")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_elevation_m");

                    b.Property<decimal?>("InitialMovingHours")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_moving_hours");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("PurchasePlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purchase_place");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("bike", "bt");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Bike.BikeLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalService")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_service");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("ExternalService", "ExternalId")
                        .IsUnique();

                    b.ToTable("bike_link", "bt");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Club.ClubEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityTypesIcon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_types_icon");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<string>("CoverPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cover_photo");

                    b.Property<string>("CoverPhotoSmall")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cover_photo_small");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_count");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<string>("Profile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile");

                    b.Property<string>("ProfileMedium")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_medium");

                    b.Property<string>("SportType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sport_type");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("state");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("club", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Component.ComponentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<decimal>("InitialDistanceKm")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_distance_km");

                    b.Property<decimal?>("InitialElevationM")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_elevation_m");

                    b.Property<decimal?>("InitialMovingHours")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_moving_hours");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("PurchasePlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purchase_place");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("component", "bt");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.KomTakeoverEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<int>("LostKomsSummaryId")
                        .HasColumnType("integer")
                        .HasColumnName("lost_koms_summary_id");

                    b.Property<long>("LostSegmentEffortId")
                        .HasColumnType("bigint")
                        .HasColumnName("lost_segment_effort_id");

                    b.Property<bool>("Reverted")
                        .HasColumnType("boolean")
                        .HasColumnName("reverted");

                    b.Property<int>("TakenKomsSummaryId")
                        .HasColumnType("integer")
                        .HasColumnName("taken_koms_summary_id");

                    b.Property<long>("TakenSegmentEffortId")
                        .HasColumnType("bigint")
                        .HasColumnName("taken_segment_effort_id");

                    b.Property<DateTime>("TrackDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("track_date");

                    b.HasKey("Id");

                    b.HasIndex("LostSegmentEffortId");

                    b.HasIndex("TakenSegmentEffortId")
                        .IsUnique();

                    b.ToTable("kom_takeover", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.KomsSummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<int>("ImprovedKoms")
                        .HasColumnType("integer")
                        .HasColumnName("improved_koms");

                    b.Property<int>("Koms")
                        .HasColumnType("integer")
                        .HasColumnName("koms");

                    b.Property<int>("LostKoms")
                        .HasColumnType("integer")
                        .HasColumnName("lost_koms");

                    b.Property<int>("NewKoms")
                        .HasColumnType("integer")
                        .HasColumnName("new_koms");

                    b.Property<int>("ReturnedKoms")
                        .HasColumnType("integer")
                        .HasColumnName("returned_koms");

                    b.Property<DateTime>("TrackDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("track_date");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "TrackDate");

                    b.ToTable("koms_summary", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.KomsSummarySegmentEffortEntity", b =>
                {
                    b.Property<int>("KomSummaryId")
                        .HasColumnType("integer")
                        .HasColumnName("koms_summary_id");

                    b.Property<long>("SegmentEffortId")
                        .HasColumnType("bigint")
                        .HasColumnName("segment_effort_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<bool>("ImprovedKom")
                        .HasColumnType("boolean")
                        .HasColumnName("improved_kom");

                    b.Property<bool>("Kom")
                        .HasColumnType("boolean")
                        .HasColumnName("kom");

                    b.Property<bool>("LostKom")
                        .HasColumnType("boolean")
                        .HasColumnName("lost_kom");

                    b.Property<bool>("NewKom")
                        .HasColumnType("boolean")
                        .HasColumnName("new_kom");

                    b.Property<bool>("ReturnedKom")
                        .HasColumnType("boolean")
                        .HasColumnName("returned_kom");

                    b.HasKey("KomSummaryId", "SegmentEffortId");

                    b.HasIndex("SegmentEffortId");

                    b.ToTable("koms_summary_segment_effort", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.SegmentEffortEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("real")
                        .HasColumnName("average_cadence");

                    b.Property<float?>("AverageHeartrate")
                        .HasColumnType("real")
                        .HasColumnName("average_heartrate");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("real")
                        .HasColumnName("average_watts");

                    b.Property<bool>("DeviceWatts")
                        .HasColumnType("boolean")
                        .HasColumnName("device_watts");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<int>("EndIndex")
                        .HasColumnType("integer")
                        .HasColumnName("end_index");

                    b.Property<int?>("KomRank")
                        .HasColumnType("integer")
                        .HasColumnName("kom_rank");

                    b.Property<float?>("MaxHeartrate")
                        .HasColumnType("real")
                        .HasColumnName("max_heartrate");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PrRank")
                        .HasColumnType("integer")
                        .HasColumnName("pr_rank");

                    b.Property<long>("SegmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("segment_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_local");

                    b.Property<int>("StartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("start_index");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("SegmentId");

                    b.ToTable("segment_effort", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.SegmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("AthleteCount")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_count");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<float>("AverageGrade")
                        .HasColumnType("real")
                        .HasColumnName("average_grade");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<int>("ClimbCategory")
                        .HasColumnType("integer")
                        .HasColumnName("climb_category");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<int?>("EffortCount")
                        .HasColumnType("integer")
                        .HasColumnName("effort_count");

                    b.Property<float>("ElevationHigh")
                        .HasColumnType("real")
                        .HasColumnName("elevation_high");

                    b.Property<float>("ElevationLow")
                        .HasColumnType("real")
                        .HasColumnName("elevation_low");

                    b.Property<float>("EndLatitude")
                        .HasColumnType("real")
                        .HasColumnName("end_latitude");

                    b.Property<float>("EndLongitude")
                        .HasColumnType("real")
                        .HasColumnName("end_longitude");

                    b.Property<bool>("Hazardous")
                        .HasColumnType("boolean")
                        .HasColumnName("hazardous");

                    b.Property<string>("MapPolyline")
                        .HasColumnType("text")
                        .HasColumnName("map_polyline");

                    b.Property<float>("MaximumGrade")
                        .HasColumnType("real")
                        .HasColumnName("maximum_grade");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<int?>("StarCount")
                        .HasColumnType("integer")
                        .HasColumnName("star_count");

                    b.Property<bool>("Starred")
                        .HasColumnType("boolean")
                        .HasColumnName("starred");

                    b.Property<float>("StartLatitude")
                        .HasColumnType("real")
                        .HasColumnName("start_latitude");

                    b.Property<float>("StartLongitude")
                        .HasColumnType("real")
                        .HasColumnName("start_longitude");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("real")
                        .HasColumnName("total_elevation_gain");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("segment", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.ActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AchievementCount")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_count");

                    b.Property<int>("AthleteCount")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_count");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cadence");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heartrate");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_speed");

                    b.Property<int?>("AverageTemp")
                        .HasColumnType("integer")
                        .HasColumnName("average_temp");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("average_watts");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<bool>("Commute")
                        .HasColumnType("boolean")
                        .HasColumnName("commute");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_name");

                    b.Property<bool>("DeviceWatts")
                        .HasColumnType("boolean")
                        .HasColumnName("device_watts");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<double?>("ElevHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("elev_high");

                    b.Property<double?>("ElevLow")
                        .HasColumnType("double precision")
                        .HasColumnName("elev_low");

                    b.Property<double?>("EndLat")
                        .HasColumnType("double precision")
                        .HasColumnName("end_lat");

                    b.Property<double?>("EndLng")
                        .HasColumnType("double precision")
                        .HasColumnName("end_lng");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged");

                    b.Property<string>("GearId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gear_id");

                    b.Property<bool>("HasHeartrate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_heartrate");

                    b.Property<double?>("Kilojoules")
                        .HasColumnType("double precision")
                        .HasColumnName("kilojoules");

                    b.Property<int>("KudosCount")
                        .HasColumnType("integer")
                        .HasColumnName("kudos_count");

                    b.Property<bool>("Manual")
                        .HasColumnType("boolean")
                        .HasColumnName("manual");

                    b.Property<double?>("MaxHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("max_heartrate");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed");

                    b.Property<double?>("MaxWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("max_watts");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("photo_count");

                    b.Property<int>("PrCount")
                        .HasColumnType("integer")
                        .HasColumnName("pr_count");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sport_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<double?>("StartLat")
                        .HasColumnType("double precision")
                        .HasColumnName("start_lat");

                    b.Property<double?>("StartLng")
                        .HasColumnType("double precision")
                        .HasColumnName("start_lng");

                    b.Property<double?>("SufferScore")
                        .HasColumnType("double precision")
                        .HasColumnName("suffer_score");

                    b.Property<string>("SummaryPolyline")
                        .HasColumnType("text")
                        .HasColumnName("summary_polyline");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("double precision")
                        .HasColumnName("total_elevation_gain");

                    b.Property<int>("TotalPhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_photo_count");

                    b.Property<bool>("Trainer")
                        .HasColumnType("boolean")
                        .HasColumnName("trainer");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<long?>("UploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_id");

                    b.Property<double>("UtcOffset")
                        .HasColumnType("double precision")
                        .HasColumnName("utc_offset");

                    b.Property<string>("Visibility")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.Property<double?>("WeightedAverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("weighted_average_watts");

                    b.Property<int?>("WorkoutType")
                        .HasColumnType("integer")
                        .HasColumnName("workout_type");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("GearId");

                    b.ToTable("activity", "strava");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.ActivitySyncHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivitiesCount")
                        .HasColumnType("integer")
                        .HasColumnName("activities_count");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_count");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sync_from");

                    b.Property<int>("UpsertedCount")
                        .HasColumnType("integer")
                        .HasColumnName("upserted_count");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("activity_sync_history", "strava");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.AthleteSyncEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<bool>("ActivitiesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("activities_enabled");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<bool>("BikesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bikes_enabled");

                    b.HasKey("AthleteId");

                    b.ToTable("athlete_sync", "strava");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.StravaBikeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("BrandName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand_name");

                    b.Property<double>("ConvertedDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("converted_distance");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int?>("FrameType")
                        .HasColumnType("integer")
                        .HasColumnName("frame_type");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nickname");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("primary");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean")
                        .HasColumnName("retired");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PK_bike1");

                    b.HasIndex("AthleteId");

                    b.ToTable("bike", "strava");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Token.TokenEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access-token");

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("refresh-token");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope");

                    b.Property<string>("TokenType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("token_type");

                    b.HasKey("AthleteId");

                    b.ToTable("token", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Warehouse.WarehouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditCD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_cd");

                    b.Property<DateTime?>("AuditMD")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_md");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("warehouse", "bt");
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.RoleClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claim", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claim", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserLoginEntity", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserRoleEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserTokenEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_token", (string)null);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteClubEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomTracker.Domain.Entities.Club.ClubEntity", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteStatsEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", "Athlete")
                        .WithOne("Stats")
                        .HasForeignKey("KomTracker.Domain.Entities.Athlete.AthleteStatsEntity", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Bike.BikeEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Bike.BikeLinkEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Bike.BikeEntity", null)
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Component.ComponentEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomTracker.Domain.Entities.Warehouse.WarehouseEntity", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.KomsSummarySegmentEffortEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Segment.KomsSummaryEntity", "KomsSummary")
                        .WithMany()
                        .HasForeignKey("KomSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomTracker.Domain.Entities.Segment.SegmentEffortEntity", "SegmentEffort")
                        .WithMany()
                        .HasForeignKey("SegmentEffortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KomsSummary");

                    b.Navigation("SegmentEffort");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Segment.SegmentEffortEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomTracker.Domain.Entities.Segment.SegmentEntity", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.ActivityEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.ActivitySyncHistoryEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.AthleteSyncEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Strava.StravaBikeEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Token.TokenEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", "Athlete")
                        .WithOne("Token")
                        .HasForeignKey("KomTracker.Domain.Entities.Token.TokenEntity", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Warehouse.WarehouseEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.RoleClaimEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserClaimEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserEntity", b =>
                {
                    b.HasOne("KomTracker.Domain.Entities.Athlete.AthleteEntity", "Athlete")
                        .WithOne()
                        .HasForeignKey("KomTracker.Infrastructure.Identity.Entities.UserEntity", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserLoginEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Infrastructure.Identity.Entities.UserTokenEntity", b =>
                {
                    b.HasOne("KomTracker.Infrastructure.Identity.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomTracker.Domain.Entities.Athlete.AthleteEntity", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
