version: "3.9"

services:
  kom-tracker-api:
    image: karql/kom-tracker-api:prod
    restart: always
    environment:
      ConnectionStrings__DB: ${CONNECTION_STRING}
      StravaApiClientConfiguration__ClientID: ${STRAVA_API_CLIENT_ID}
      StravaApiClientConfiguration__ClientSecret: ${STRAVA_API_CLIENT_SECRET}
      IdentityConfiguration__IdentityUrl: https://komtracker.karkula.pl/kom-tracker-api/identity
      IdentityConfiguration__RedirectUris__0: https://komtracker.karkula.pl

  postgres:
    image: postgres:14.0
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data
    volumes:
      - /u01/volumes/kom-tracker-prod/postgres/data:/data
    ports:
      - 5432:5432
