version: "3.9"

services:
  kom-tracker-api:
    image: karql/kom-tracker-api:prod
    restart: always
    environment:
      ConnectionStrings__DB: ${CONNECTION_STRING}
      ApiConfiguration__KeysPath: /keys
      ApplicationConfiguration__MasterStravaAthleteId: ${APP_CONF_MASTER_STRAVA_ATHLETE_ID}
      ApplicationConfiguration__SendinBlueConfiguration__ApiKey: ${APP_CONF_SENDINBLUE_API_KEY}
      ApplicationConfiguration__SendinBlueConfiguration__ChangeEmailConfirmationTemplateId: 7
      ApplicationConfiguration__SendinBlueConfiguration__TrackKomsTemplateId: 3
      StravaApiClientConfiguration__ClientID: ${STRAVA_API_CLIENT_ID}
      StravaApiClientConfiguration__ClientSecret: ${STRAVA_API_CLIENT_SECRET}
      IdentityConfiguration__IdentityUrl: https://komtracker.karkula.pl/kom-tracker-api/identity
      IdentityConfiguration__Authority: https://komtracker.karkula.pl/kom-tracker-api/identity
      IdentityConfiguration__RequireHttpsMetadata: "true"
      IdentityConfiguration__RedirectUris__0: https://komtracker.karkula.pl
      IdentityConfiguration__RedirectUris__1: https://localhost
    volumes:
      - /u01/volumes/kom-tracker-prod/kom-tracker-api/keys:/keys

  kom-tracker-web:
    image: karql/kom-tracker-web:prod
    restart: always
    volumes:
      - ./conf/kom-tracker-web/appsettings.json:/app/appsettings.json

  postgres:
    image: postgres:14.0
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data
    volumes:
      - /u01/volumes/kom-tracker-prod/postgres/data:/data
    ports:
      - 5432:5432